### ISSUE TITLE
Question: Can you add examples?

### ISSUE THREAD

**Issue by trotha01** [circuithub/elm-bootstrap-html#2]
I'm just getting up and running with Elm, could you add some examples of using this library? Or links to some?

I think a few examples of using your bootstrap library would be extremely helpful, and could help others get up and running much quicker. Even a simple, press-the-button and something happens example would be great.

**Comment by rehno-lindeque** [comment]
I'll give it a shot... I'll try and publish one or two examples soon.

**Comment by rehno-lindeque** [comment]
It's not much but I quickly threw together examples for three tags: 
- [tableStriped'](http://package.elm-lang.org/packages/circuithub/elm-bootstrap-html/6.0.2/Bootstrap-Html#tableStriped')
- [tableBodyStriped'](http://package.elm-lang.org/packages/circuithub/elm-bootstrap-html/6.0.2/Bootstrap-Html#tableBodyStriped')
- [panelDefault'](http://package.elm-lang.org/packages/circuithub/elm-bootstrap-html/6.0.2/Bootstrap-Html#panelDefault')

This package is not very mature unfortunately - if you want to use it in practice you'll probably need to extend it for whatever purpose you'd like (I'm happy to give push access to this repo to anyone seriously contemplating doing this). I initially planned to replicate the bootstrap website's documentation in [this gh-pages branch](https://github.com/circuithub/elm-bootstrap/tree/gh-pages) in order to make sure that the library is complete & documented. However, unfortunately don't have the manpower to properly maintain this package at the moment, so please take this disclaimer into account!

**Comment by trotha01** [comment]
Thank you very much for the examples! No worries if it's not mature yet. I'm still learning Elm, but I can try and contribute as I learn more. 

And that is awesome you are making a gh-pages branch!
